//Gilbert_De_Benedetti.js
window.musicas = [
   { name: "23615 - Twinkle, Twinkle Little Star", file: "pdf/23615 - Twinkle, Twinkle Little Star - Arr Gilbert DeBenedetti - Primer A.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" }, 
  { name: "23645 - Bullock Cart", file: "pdf/23645 - Bullock Cart - Arr Gilbert DeBenedetti - FirstPiecesA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "First Pieces A" },
  { name: "23646 - Fathers Whiskers", file: "pdf/23646 - Fathers Whiskers - Arr Gilbert DeBenedetti - FirstPiecesA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "First Pieces A" },
  { name: "23648 - Everywhere We Go", file: "pdf/23648 - Everywhere We Go - Arr Gilbert DeBenedetti - FirstPiecesB.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "First Pieces B" },
  { name: "23667 - Such Getting Upstairs", file: "pdf/23667 - Such Getting Upstairs - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23651 - Nobody Likes Me", file: "pdf/23651 - Nobody Likes Me - Arr Gilbert DeBenedetti - FirstPiecesB.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "First Pieces B" },
  { name: "23621 - Old MacDonald Had a Farm", file: "pdf/23621 - Old MacDonald Had a Farm - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", level: "Primer A" },
  { name: "23668 - Thats Where My Money", file: "pdf/23668 - Thats Where My Money - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23653 - Pop Goes the Weasel", file: "pdf/23653 - Pop Goes the Weasel - Arr Gilbert DeBenedetti - FirstPiecesB.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "FirstPiecesB" }, 
  { name: "23658 - Blow the Man Down", file: "pdf/23658 - Blow the Man Down - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23662 - Goodbye Old Paint", file: "pdf/23662 - Goodbye Old Paint - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23669 - The Animal Fair", file: "pdf/23669 - The Animal Fair - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23673 - Yonder She Comes", file: "pdf/23673 - Yonder She Comes - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23655 - This Little Light of Mine", file: "pdf/23655 - This Little Light of Mine - Arr Gilbert DeBenedetti - FirstPiecesB.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "First Pieces B" },
  { name: "23616 - Gray Squirrel", file: "pdf/23616 - Gray Squirrel - Arr Gilbert DeBenedetti - Primer A.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23628 - Clementine", file: "pdf/23628 - Clementine - Arr Gilbert DeBenedetti - Primer B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer B" },
  { name: "23661 - Goodbye Julie", file: "pdf/23661 - Goodbye Julie - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23618 - Away in a Manger", file: "pdf/23618 - Away in a Manger - Arr Gilbert DeBenedetti - Primer A.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23624 - Away in a Manger", file: "pdf/23624 - Away in a Manger - Arr Gilbert DeBenedetti - Primer A.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23665 - Michael Finnegan", file: "pdf/23665 - Michael Finnegan - Arr Gilbert DeBenedetti - PrimerA.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer A" },
  { name: "23680 - Have You Ever Seen A Fishy", file: "pdf/23680 - Have You Ever Seen A Fishy - Arr Gilbert DeBenedetti - PrimerC.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer C" },
  { name: "23690 - Bullock Cart", file: "pdf/23690 - Bullock Cart - Arr Gilbert DeBenedetti - Beginner1B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Beginner 1B" },
  { name: "23691 - Great Green Globs", file: "pdf/23691 - Great Green Globs - Arr Gilbert DeBenedetti - Beginner1B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Beginner 1B" },
  { name: "23693 - I Heard a Robin Singing", file: "pdf/23693 - I Heard a Robin Singing - Arr Gilbert DeBenedetti - Beginner1B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Beginner 1B" },
  { name: "23694 - Old Blue", file: "pdf/23694 - Old Blue - Arr Gilbert DeBenedetti - Beginner1B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Beginner 1B" },
  { name: "23695 - Second Story Window", file: "pdf/23695 - Second Story Window - Arr Gilbert DeBenedetti - Beginner1B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Beginner 1B" },
  { name: "23683 - Calavera", file: "pdf/23683 - Calavera - Arr Gilbert DeBenedetti - Beginner1A.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Beginner 1A" },
  { name: "23684 - Li'l Liza Jane", file: "pdf/23684 - Li'l Liza Jane - Arr Gilbert DeBenedetti - Beginner1A.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Beginner 1A" },
  { name: "23625 - The Arkansas Traveler", file: "pdf/23625 - The Arkansas Traveler - Arr Gilbert DeBenedetti - Primer B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer B" },
  { name: "23626 - The Baby Bumble Bee", file: "pdf/23626 - The Baby Bumble Bee - Arr Gilbert DeBenedetti - Primer B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer B" },
  { name: "23630 - Amazing Grace", file: "pdf/23630 - Amazing Grace - Arr Gilbert DeBenedetti - Primer B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer B" },
  { name: "23632 - We Gather Together", file: "pdf/23632 - We Gather Together - Arr Gilbert DeBenedetti - Primer B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer B" },
  { name: "23635 - Oh, When the Saints", file: "pdf/23635 - Oh, When the Saints - Arr Gilbert DeBenedetti - Primer B.pdf", composer: "Arr Gilbert DeBenedetti", reference: "6991-PDF-Piano", level: "Primer B" },
  
];