window.nivel2 = [

  { nome: "Arr Gilbert DeBenedetti", arquivo: "js/nivel1/compositor/Arr_Gilbert_DeBenedetti.js" },
  { nome: "Beethoven", arquivo: "js/nivel1/compositor/Beethoven.js" },
  { nome: "Charles Connolly", arquivo: "js/nivel1/compositor/Charles_Connolly.js" },
  { nome: "England", arquivo: "js/nivel1/compositor/England.js" },
  { nome: "Franz Joseph Haydn", arquivo: "js/nivel1/compositor/Franz_Joseph_Haydn.js" },
  { nome: "George R. Poulton", arquivo: "js/nivel1/compositor/George_R._Poulton.js" },
  { nome: "Gilbert DeBenedetti", arquivo: "js/nivel1/compositor/Gilbert_DeBenedetti.js" },
  { nome: "Giuseppe Verdi", arquivo: "js/nivel1/compositor/Giuseppe_Verdi.js" },
  { nome: "Harry Lauder", arquivo: "js/nivel1/compositor/Harry_Lauder.js" },
  { nome: "India", arquivo: "js/nivel1/compositor/India.js" },
  { nome: "Italy", arquivo: "js/nivel1/compositor/Italy.js" },
  { nome: "J. Pierpont", arquivo: "js/nivel1/compositor/J._Pierpont.js" },
  { nome: "J.S. Bach", arquivo: "js/nivel1/compositor/J.S._Bach.js" },
  { nome: "Jean-Paul-ègide Martini", arquivo: "js/nivel1/compositor/Jean_Paul_ègide_Martini.js" },
  { nome: "Jewish, for Passover", arquivo: "js/nivel1/compositor/Jewish_for_Passover.js" },
  { nome: "Johannes Brahms", arquivo: "js/nivel1/compositor/Johannes_Brahms.js" },
  { nome: "John Henry Hopkins", arquivo: "js/nivel1/compositor/John_Henry_Hopkins.js" },
  { nome: "Michael Verbytskyi", arquivo: "js/nivel1/compositor/Michael_Verbytskyi.js" },
  { nome: "Naples, Italy", arquivo: "js/nivel1/compositor/Naples_Italy.js" },
  { nome: "Patty and Mildred Hill", arquivo: "js/nivel1/compositor/Patty_and_Mildred_Hill.js" },
  { nome: "Pyotr Ilyich Tchaikovsky", arquivo: "js/nivel1/compositor/Pyotr_Ilyich_Tchaikovsky.js" },
  { nome: "Richard Wagner", arquivo: "js/nivel1/compositor/Richard_Wagner.js" },
  { nome: "Stephen Foster", arquivo: "js/nivel1/compositor/Stephen_Foster.js" },
  { nome: "Traditional", arquivo: "js/nivel1/compositor/Traditional.js" },
  { nome: "Traditional English", arquivo: "js/nivel1/compositor/Traditional_English.js" },
  { nome: "Traditional Fiddle Tune", arquivo: "js/nivel1/compositor/Traditional_Fiddle_Tune.js" },
  { nome: "Traditional Irish", arquivo: "js/nivel1/compositor/Traditional_Irish.js" },
  { nome: "Traditional Jewish", arquivo: "js/nivel1/compositor/Traditional_Jewish.js" },
  { nome: "Traditional Mexican", arquivo: "js/nivel1/compositor/Traditional_Mexican.js" },
  { nome: "Tradtional Russian", arquivo: "js/nivel1/compositor/Tradtional_Russian.js" },
  { nome: "W.A. Mozart", arquivo: "js/nivel1/compositor/W.A._Mozart.js" },
  { nome: "William S. Allen", arquivo: "js/nivel1/compositor/William_S._Allen.js" },
  { nome: "Yiddish", arquivo: "js/nivel1/compositor/Yiddish.js" },

];
