//Gilbert_De_Benedetti.js
window.musicas = [
  { name: "23581 - Hot Cross Buns", file: "pdf/23581 - Hot Cross Buns - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23582 - Mary Had a Little Lamb", file: "pdf/23582 - Mary Had a Little Lamb - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },  
  { name: "23583 - Au Clair de la Lune", file: "pdf/23583 - Au Clair de la Lune - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23584 - Rain, Rain, Go Away", file: "pdf/23584 - Rain, Rain, Go Away - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23585 - Jingle Bells", file: "pdf/23585 - Jingle Bells - J. Pierpont - A.pdf", composer: "J. Pierpont", level: "A" },
  { name: "23586 - Aura Lee", file: "pdf/23586 - Aura Lee - George R. Poulton - A.pdf", composer: "George R. Poulton", level: "A" },
  { name: "23587 - Do, Do l'Enfant Do", file: "pdf/23587 - Do, Do l'Enfant Do - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23588 - A Tisket, a Tasket", file: "pdf/23588 - A Tisket, a Tasket - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23589 - Ode to Joy", file: "pdf/23589 - Ode to Joy - Beethoven - A.pdf", composer: "Beethoven", level: "A" },
  { name: "23590 - Good King Wenceslas", file: "pdf/23590 - Good King Wenceslas - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23591 - Sweetly Sings the Donkey", file: "pdf/23591 - Sweetly Sings the Donkey - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23592 - Go Tell Aunt Rhodie", file: "pdf/23592 - Go Tell Aunt Rhodie - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23593 - Row, Row, Row Y our Boat", file: "pdf/23593 - Row, Row, Row Y our Boat - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23594 - Camptown Races", file: "pdf/23594 - Camptown Races - Stephen Foster - A.pdf", composer: "Stephen Foster", level: "A" },
  { name: "23595 - For Health and Strength", file: "pdf/23595 - For Health and Strength - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23596 - We Three Kings", file: "pdf/23596 - We Three Kings - John Henry Hopkins - A.pdf", composer: "John Henry Hopkins", level: "A" },
  { name: "23597 - I Saw Three Ships", file: "pdf/23597 - I Saw Three Ships - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23598 - Banks of the Ohio", file: "pdf/23598 - Banks of the Ohio - Traditional - A.pdf", composer: "Traditional", level: "A" },
  { name: "23599 - In the Field Stood a Birch Tree", file: "pdf/23599 - In the Field Stood a Birch Tree - Tradtional Russian - A.pdf", composer: "Tradtional Russian", level: "A" },
  { name: "23600 - Richard Wagner", file: "pdf/23600 - Richard Wagner - Bridal March - A.pdf", composer: "Bridal March", level: "A" },
  { name: "23601 - Mexican Hat Dance", file: "pdf/23601 - Mexican Hat Dance - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23602 - Theme to Swan Lake", file: "pdf/23602 - Theme to Swan Lake - Pyotr Ilyich Tchaikovsky - A.pdf", composer: "Pyotr Ilyich Tchaikovsky", level: "A" },
  { name: "23603 - Away in the Deep Forest", file: "pdf/23603 - Away in the Deep Forest - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23604 - Jolly Old Saint Nicholas", file: "pdf/23604 - Jolly Old Saint Nicholas - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23605 - Once a Small Green Mousie", file: "pdf/23605 - Once a Small Green Mousie - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23606 - Fais Dodo", file: "pdf/23606 - Fais Dodo - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23607 - Auld Lang Syne", file: "pdf/23607 - Auld Lang Syne - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23608 - London Bridge", file: "pdf/23608 - London Bridge - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23609 - Les Cloches", file: "pdf/23609 - Les Cloches - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23610 - Five Fat Turkeys Are We", file: "pdf/23610 - Five Fat Turkeys Are We - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23611 - Yankee Doodle", file: "pdf/23611 - Yankee Doodle - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23612 - There's a Hole in My Bucket", file: "pdf/23612 - There's a Hole in My Bucket - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" },
  { name: "23613 - Happy Birthday to You", file: "pdf/23613 - Happy Birthday to You - Patty and Mildred Hill - A.pdf", composer: "Patty and Mildred Hill", level: "A" },
  { name: "23614 - We Wish You a Merry Christmas", file: "pdf/23614 - We Wish You a Merry Christmas - Arr Gilbert DeBenedetti - A.pdf", composer: "Arr Gilbert DeBenedetti", level: "A" }


];
