const planoDeAula = {
  "nomePlano": "dedo",
  "segmento": "Ensino Médio",
  "turma": "1ª Série",
  "duracao": "aaddas",
  "areaConhecimento": "asdasda",
  "eixo": "adadad",
  "habilidades": "",
  "competencia": "",
  "tema": "",
  "justificativa": "",
  "objetivosGerais": "",
  "objetivosEspecificos": "",
  "conteudos": "",
  "metodologia": "",
  "encaminhamento": "",
  "tecnica": "",
  "teoria": "",
  "leitura": "",
  "recursos": "",
  "roteiro": "",
  "atividadeClasse": "",
  "atividadeCasa": "",
  "avaliacao": "",
  "nivelTecnico": "",
  "comportamentos": "",
  "desenvolvimento": "",
  "observacoes": "",
  "registro": ""
};