const planoDeAula = {
  "segmento": "Educação Infantil",
  "turma": "Turma EI 1",
  "duracao": "assassasasssASas",
  "areaConhecimento": "saSAAaSasASAsAaaSsaSas",
  "eixo": "",
  "habilidades": "",
  "competencia": "",
  "tema": "",
  "justificativa": "",
  "objetivosGerais": "",
  "objetivosEspecificos": "",
  "conteudos": "",
  "metodologia": "",
  "encaminhamento": "",
  "tecnica": "",
  "teoria": "",
  "leitura": "",
  "recursos": "",
  "roteiro": "",
  "atividadeClasse": "",
  "atividadeCasa": "",
  "avaliacao": "",
  "nivelTecnico": "",
  "comportamentos": "",
  "desenvolvimento": "",
  "observacoes": "",
  "registro": ""
};