var plano = {
  "segmento": "Educação Infantil",
  "turma": "Grupo 3",
  "duracao": "dass",
  "areaConhecimento": "dasd",
  "eixo": "adasda",
  "habilidades": "adadasas",
  "competencia": "dasd",
  "tema": "adas",
  "justificativa": "adasd",
  "objetivosGerais": "dasd",
  "objetivosEspecificos": "asdas",
  "conteudos": "asdasd",
  "metodologia": "adasd",
  "encaminhamento": "adas",
  "tecnica": "adas",
  "teoria": "adasd",
  "leitura": "adsa",
  "recursos": "adas",
  "roteiro": "asdsa",
  "atividadeClasse": "asdsa",
  "atividadeCasa": "adasa",
  "avaliacao": "dasd",
  "nivelTecnico": "asdsa",
  "comportamentos": "adsasdasd",
  "desenvolvimento": "adsdasd",
  "observacoes": "adas",
  "registro": "asdasdad"
};
