const planoDeAula = {
  "segmento": "Ensino Fundamental",
  "turma": "Grupo 3",
  "duracao": "Beto",
  "areaConhecimento": "",
  "eixo": "",
  "habilidades": "",
  "competencia": "",
  "tema": "",
  "justificativa": "",
  "objetivosGerais": "",
  "objetivosEspecificos": "",
  "conteudos": "",
  "metodologia": "",
  "encaminhamento": "",
  "tecnica": "",
  "teoria": "",
  "leitura": "",
  "recursos": "",
  "roteiro": "",
  "atividadeClasse": "",
  "atividadeCasa": "",
  "avaliacao": "",
  "nivelTecnico": "",
  "comportamentos": "",
  "desenvolvimento": "",
  "observacoes": "",
  "registro": ""
};