window.nivel2 = [

  { nome: "Arr Gilbert DeBenedetti" },
  { nome: "Beethoven" },
  { nome: "Bridal March" },
  { nome: "Charles Connolly" },
  { nome: "England" },
  { nome: "Franz Joseph Haydn" },
  { nome: "Gilbert DeBenedetti" },
  { nome: "Giuseppe Verdi" },
  { nome: "Harry Lauder" },
  { nome: "India" },
  { nome: "Italia" },
  { nome: "Italy" },
  { nome: "J. Pierpont" },
  { nome: "J.S. Bach" },
  { nome: "Jacques Offenbach" },
  { nome: "Jean-Paul-ègide Martini" },
  { nome: "Jewish, for Passover" },
  { nome: "Johannes Brahms" },
  { nome: "John Henry Hopkins" },
  { nome: "Michael Verbytskyi" },
  { nome: "Naples, Italy" },
  { nome: "New Zealand Sea Shanty" },
  { nome: "Old English" },
  { nome: "Patty and Mildred Hill" },
  { nome: "Pyotr Ilyich Tchaikovsky" },
  { nome: "Stephen Foster" },
  { nome: "Thomas Haynes Bailey" },
  { nome: "Tradtional Russian" },
  { nome: "Traditional" },
  { nome: "Traditional Fiddle Tune" },
  { nome: "Traditional Irish" },
  { nome: "Traditional Jewish" },
  { nome: "Traditional Mexican" },
  { nome: "William S. Allen" },
  { nome: "Yiddish" }

    // ...
];