const availableMidis = [
    { name: "Exemplo 1 - Pop", path: "midis/exemplo1.mid" },
    { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
        { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
        { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
        { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
        { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
        { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
        { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
        { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
        { name: "Exemplo 2 - Rock", path: "midis/exemplo2.mid" },
    { name: "Exemplo 3 - Jazz", path: "midis/exemplo3.mid" },
    { name: "Exemplo 4 - Clássico", path: "midis/exemplo4.mid" },
    
    { name: "Exemplo 5 - Eletrônico", path: "midis/exemplo5.mid" }
  ];
